"""Rule catalogue. Every rule cites the Gradle documentation section it comes from."""
from __future__ import annotations

from dataclasses import dataclass

U8 = "https://docs.gradle.org/current/userguide/upgrading_version_8.html"
U9 = "https://docs.gradle.org/current/userguide/upgrading_version_9.html"


@dataclass(frozen=True)
class Rule:
    id: str
    severity: str  # error: documented as removed/failing in Gradle 10 and detected reliably; warning: documented, but detection is heuristic
    summary: str
    fix: str
    url: str
    fixable: bool = False
    oracle: bool = True  # True: checked against real Gradle in tests/oracle. False: taken from the Gradle docs, pattern-tested only


RULES: dict = {r.id: r for r in [
    Rule("space-assignment", "error",
         "Groovy 'propertyName value' (space assignment) is generated by Gradle and removed in Gradle 10",
         "Write `propertyName = value`.", U8 + "#groovy_space_assignment_syntax", True),
    Rule("space-assignment-android", "warning",
         "Groovy 'propertyName value' on an Android Gradle Plugin property (namespace, viewBinding, abortOnError, ...) relies on the same generated method",
         "Write `propertyName = value`.", U8 + "#groovy_space_assignment_syntax", True),
    Rule("multi-string-dependency", "error",
         "Map / named-argument dependency notation (group, name, version) is removed in Gradle 10",
         "Use the single string `group:name:version`.", U9 + "#dependency_multi_string_notation", True),
    Rule("kotlin-dsl-delegate", "error",
         "Kotlin DSL property delegates (by project / extra / settings / registering / creating / existing / getting) are removed in Gradle 10",
         "Use the explicit API, for example `project.property(\"p\")`, `extra[\"p\"]`, `tasks.register(\"x\")`.", U9 + "#kotlin_dsl_delegated_properties", True),
    Rule("project-properties", "error",
         "Project.getProperties() / project.properties is removed in Gradle 10",
         "Use `providers.gradleProperty(\"name\")` or `project.findProperty(\"name\")`.", U9 + "#deprecated_get_properties"),
    Rule("test-closure-methods", "error",
         "Test task methods taking a Groovy Closure (beforeTest, afterTest, beforeSuite, afterSuite, onOutput) are removed in Gradle 10",
         "Register a TestListener / TestOutputListener with addTestListener / addTestOutputListener.", U9 + "#deprecated_test_methods"),
    Rule("flatdir-map", "error",
         "RepositoryHandler.flatDir(Map) and mavenCentral(Map) are removed in Gradle 10",
         "Use the closure form: `flatDir { dirs 'libs' }`.", U9 + "#deprecated_repository_handler_map_overloads"),
    Rule("artifact-urls", "error",
         "MavenArtifactRepository.artifactUrls is removed in Gradle 10 (no replacement)",
         "Publish POM and artifacts at the same base URL.", U9 + "#deprecated_maven_artifact_urls"),
    Rule("archives-configuration", "warning",
         "The `archives` configuration is deprecated and removed in Gradle 10",
         "Add the artifact as a dependency of `assemble` instead.", U9 + "#archives-configuration"),
    Rule("build-needed-dependents", "warning",
         "The buildNeeded and buildDependents tasks are removed in Gradle 10",
         "Run the specific tasks (`./gradlew :proj:build`) or use test report aggregation.", U9 + "#deprecate_build_needed_build_dependents_tasks", oracle=False),
    Rule("set-all-jvm-args", "error",
         "JavaForkOptions.setAllJvmArgs / allJvmArgs is removed in Gradle 10",
         "Use `jvmArgs`, `setJvmArgs` or a CommandLineArgumentProvider.", U9 + "#set-all-jvm-args"),
    Rule("project-container", "warning",
         "Project.container(...) is removed in Gradle 10",
         "Use a managed property or `objects.domainObjectContainer(...)`.", U9 + "#project_container_methods", oracle=False),
    Rule("find-all-closure", "warning",
         "DomainObjectCollection.findAll(Closure) is removed in Gradle 10",
         "Use `matching { ... }` (lazy) or `toList().findAll { ... }`.", U9 + "#findAll_removal"),
    Rule("start-parameter-build-cache", "error",
         "Enabling the build cache from build logic (startParameter.buildCacheEnabled) is removed in Gradle 10",
         "Set `org.gradle.caching=true` in gradle.properties or pass --build-cache.", U9 + "#deprecation_enabling_build_cache_from_build_logic"),
    Rule("apply-false-precompiled", "error",
         "`apply false` in a precompiled script plugin still applies the plugin and is an error in Gradle 10",
         "Remove `apply false` (to keep the plugin) or delete the line.", U9 + "#deprecate_apply_false_in_precompiled_script_plugins", oracle=False),
    Rule("reporting-extension", "error",
         "ReportingExtension.file(String) is removed in Gradle 10",
         "Use `reporting.baseDirectory` (and `file(...)` / `dir(...)` on it).", U9 + "#reporting_extension_file"),
    Rule("pmd-target-jdk", "error",
         "The PMD plugin's targetJdk is a no-op and removed in Gradle 10",
         "Delete the line.", U9 + "#deprecated_pmd_target_jdk"),
    Rule("develocity-plugin-old", "warning",
         "Develocity / Gradle Enterprise plugin versions before 4.0 rely on implicit parent-project property lookup, removed in Gradle 10",
         "Upgrade to the Develocity plugin 4.x.", U9 + "#deprecated_develocity_plugin_pre_4_0", oracle=False),
    Rule("impldep-import", "error",
         "Kotlin DSL scripts can no longer import org.gradle.internal.impldep.* (fails to compile from Gradle 9.6)",
         "Add the original library as a buildscript dependency and import it directly.", U9 + "#kotlin_dsl_impldep_compilation", oracle=False),
    Rule("tooling-parallel-implicit", "warning",
         "org.gradle.parallel=true without org.gradle.tooling.parallel: the implicit link is an error in Gradle 10 during IDE model building",
         "Add `org.gradle.tooling.parallel=true` (or false) to gradle.properties.", U9 + "#deprecate_implicit_parallel_model_building", oracle=False),
    Rule("isolated-projects-unsafe-names", "warning",
         "org.gradle.unsafe.isolated-projects* property names are deprecated",
         "Drop the `.unsafe.` segment: `org.gradle.isolated-projects`.", U9 + "#deprecated_unsafe_isolated_projects_properties", True, oracle=False),
]}
